# Setup
title:               Kleine Karibik 2024
tagline:             ''
description:         ''
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Die Kleine Karibik
  url:               
  email:             kleinekaribik@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

